import { FileText } from "lucide-react";
import React from "react";

interface Clause {
  title: string;
  explanation: string;
  example: string;
  questionsToAsk: string[];
}

interface StudentOutput {
  title: string;
  about: string;
  clauses: Clause[];
  keyLegalNotes: string[];
  finalTips: string[];
}

const StudentSummary: React.FC<{ aiRawOutput: StudentOutput }> = ({ aiRawOutput }) => {
  return (
    <div className="max-w-6xl mx-auto bg-white border border-gray-100 rounded-2xl shadow-sm p-0 flex flex-col h-[60vh]">
      {/* Fixed Header */}
      <header className="border-b px-6 py-6 bg-white rounded-t-2xl z-10 sticky top-0">
        <h1 className="text-xl font-bold text-gray-900">{aiRawOutput.title}</h1>
      </header>
      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-8">
        <section>
          <h2 className="text-lg font-semibold text-gray-900 flex items-center mb-2">
            <FileText className="w-5 h-5 mr-2" /> About
          </h2>
          <p className="text-gray-700 leading-relaxed">{aiRawOutput.about}</p>
        </section>

        {/* Clauses */}
        <section>
          <h3 className="text-lg font-semibold text-neutral-800 mb-3">Important Clauses</h3>
          <div className="space-y-4">
            {aiRawOutput.clauses.map((clause, i) => (
              <div
                key={i}
                className=" border-l-4 border-gray-500 pl-4"
              >
                <div className="font-medium text-neutral-900 mb-1">{clause.title}</div>
                <div className="text-neutral-700 text-sm">{clause.explanation}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Key Legal Notes */}
        <section>
          <h3 className="text-lg font-semibold text-neutral-800 mb-2">Key Legal Notes</h3>
          <ul className="list-disc pl-6 space-y-1 text-neutral-700 text-sm">
            {aiRawOutput.keyLegalNotes.map((n, i) => (
              <li key={i}>{n}</li>
            ))}
          </ul>
        </section>

        {/* Final Tips */}
        <section>
          <h3 className="text-lg font-semibold text-neutral-800 mb-2">Final Tips</h3>
          <ul className="list-disc pl-6 space-y-1 text-neutral-700 text-sm">
            {aiRawOutput.finalTips.map((t, i) => (
              <li key={i}>{t}</li>
            ))}
          </ul>
        </section>

        {/* Footer Branding (Web) */}
        <footer className="pt-6 mt-8 border-t border-gray-100 text-center text-xs text-neutral-400">
          Generated by <span className="font-semibold">Know Your Terms</span>
        </footer>
      </div>
    </div>
  );
};

export default StudentSummary;
